# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: JFrogToolsInstaller@1
  inputs:
    artifactoryConnection: 'hts2v2artifactory'
    cliInstallationRepo: 'jfrog-cli-v2-new'
    installCustomVersion: true
    cliVersion: '2.44.1'
    installExtractors: true
    extractorsInstallationRepo: 'extractors'
- task: JFrogMaven@1
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'install'
    artifactoryResolverService: 'hts2v2artifactory'
    targetResolveReleaseRepo: 'ado-libs-release'
    targetResolveSnapshotRepo: 'ado-libs-snapshot'
    artifactoryDeployService: 'hts2v2artifactory'
    targetDeployReleaseRepo: 'ado-generic-deploy-local-snapshot'
    targetDeploySnapshotRepo: 'ado-generic-deploy-local-release'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true
    javaHomeOption: 'JDKVersion'
- task: JFrogPublishBuildInfo@1
  inputs:
    artifactoryConnection: 'hts2v2artifactory'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
- task: JFrogBuildScan@1
  inputs:
    xrayConnection: 'hts2-v2-xray'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    allowFailBuild: false
    vuln: false